"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\mers.jpg"
"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\bmw.jpg"
"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\audi.jpg"
"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\tesla.jpg"
"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\Kia Sorento Edition 2023 UK-10.webp"
"C:\Users\HP Victus\OneDrive\Рабочий стол\picture\image.jpg"